name: Node CI

on:
  schedule:
    # Runs every 12 hours
    # - cron: '0 */12 * * *'
    # Runs every 4 days at 14:00 UTC
    - cron: '0 14 */4 * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'warning'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install ffmpeg
        run: |
          sudo apt update
          sudo apt-get install -y --no-install-recommends ffmpeg

      - name: Start project
        run: npm install

      # Additional steps to create folder, write JSON file and commit changes
      - name: Playlist run
        run: node playlist.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}